### PR TITLE
Fix/depth  Resolve debug: [object object] regular matching error in browser localStorage

### PR DESCRIPTION
**Pull request by wj0990**
It is not clear where this object is written. Cause this regular error

 in  common.js
```js
 if (namespaces[0] === '-') {
   createDebug.skips.push(new RegExp('^' + namespaces.slice(1) + '$'));
} else {
	createDebug.names.push(new RegExp('^' + namespaces + '$'));
// }
```
error

1521684460964_ pic

### CODE REVIEW

**Comment by Qix-** [comment]
Why are you passing an object to the namespaces?

**Comment by wj0990** [comment]
> 为什么要将对象传递给名称空间？

We rely on a lot of third-party libraries. These large third-party libraries all depend on your package. I don’t know where it is written. I haven’t added it to my project.

**Comment by Qix-** [comment]
You're using webpack. You should be able to turn on sourcemaps and get an accurate stacktrace as to where it's happening.

**Comment by Qix-** [comment]
Sorry, but I'm not really interested in adding this support. The library is clearly being incorrectly used somewhere, you'll need to find where that's happening and open a PR against their codebase if it's happening outside yours.

**Comment by wj0990** [comment]
> Sorry, but I'm not really interested in adding this support. The library is clearly being incorrectly used somewhere, you'll need to find where that's happening and open a PR against their codebase if it's happening outside yours.

Thanks, I tried it, but the development environment can't reproduce it
  It's a pity that I can't contribute. Several libraries in my current project dependencies depend on your package. There are more than a dozen projects of the same type nested in a desktop reference through the <ifarme> tag. The item has been in production for two years without any anomalies. The development environment has never been encountered before, that is, the recent production environment users access it from the desktop application. Several users online encountered this problem. I'm thinking of other ways.

**Pull request closed without merging**
